### ISSUE TITLE
Overwrite onSubmit function

### ISSUE THREAD

**Issue by bchhabra2490** [codeinfuse/react-multiple-datepicker#8]
I am using the component in redux-form. 
`<Field
                name="available"
                    type="text"
                    icon="file text outline"
                    placeholder="Dates"
                    component={renderCalender}
                  />`
`const renderCalendar = ({input})=>(<MultipleDatePicker onSubmit = {input.onChange} />);`
Everytime, I select a date. It automatically submits the whole form (runs onSubmit of Redux Form).

[Here's the sandbox](https://codesandbox.io/s/5w31rvpmll). Try selecting a date.

**Comment by iamsolankiamit** [comment]
It has to do with the button types not being `type="button"` on lines [43 - 44](https://github.com/BilalBudhani/react-multiple-datepicker/blob/master/example/src/lib/components/Datepicker/CalendarButtons.js#L43) and [DayButton - 107](https://github.com/BilalBudhani/react-multiple-datepicker/blob/master/example/src/lib/components/Datepicker/Week.js#L107). default button type is submit, which will run the onSubmit action of the form. 

It's a good-first-issue, can you send a pull request @BilalBudhani can review and merge it.

**Comment by bchhabra2490** [comment]
#9 Just added a pull request.Review it @BilalBudhani

**Comment by ashvin14** [comment]
is this issue closed or yet to be worked on?

**Comment by bchhabra2490** [comment]
It is closed. If you are still facing the issue, you can use https://github.com/bchhabra2490/react-multiple-datepicker. It has latest code.
